replicaCount: 1

image:
  repository: muzaparoff/barkuni-api
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Ingress configuration
domainName: test.vicarius.xyz
certificateArn: ""  # Will be set during deployment

nodeSelector: {}

tolerations: []

affinity: {} 