name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  manage-certificates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Install OpenSSL
        run: |
          sudo apt-get update
          sudo apt-get install -y openssl
      - name: Manage SSL Certificates
        run: ./scripts/manage-certificates.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
  version:
    needs: manage-certificates
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump.outputs.new_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags!
      - name: Bump version
        id: bump
        run: |
          git fetch --tags
          latest=$(git tag --list 'v*' --sort=-v:refname | head -n1)
          if [ -z "$latest" ]; then
            latest="v0.0.0"
          fi
          echo "Latest tag: $latest"
          IFS='.' read -r major minor patch <<< "${latest#v}"
          if git log -1 --pretty=%B | grep -qE "fix:"; then
            patch=$((patch+1))
          elif git log -1 --pretty=%B | grep -qE "feat:"; then
            minor=$((minor+1)); patch=0
          else
            patch=$((patch+1))
          fi
          new_tag="v${major}.${minor}.${patch}"
          if git rev-parse "$new_tag" >/dev/null 2>&1; then
            echo "Tag $new_tag already exists. Skipping tag creation."
          else
            git tag $new_tag
            git push origin $new_tag
          fi
          echo "::set-output name=new_version::$new_tag"
  build-and-push:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/barkuni-api:${{ needs.version.outputs.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/barkuni-api:latest
          platforms: linux/amd64,linux/arm64
  deploy-infra:
    needs: [build-and-push, manage-certificates]
    runs-on: ubuntu-latest
    container:
      image: muzaparoff/terraform-runner:latest
      options: --platform=linux/amd64
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      CLUSTER_NAME: barkuni-exam-cluster
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Init and Apply (Infrastructure)
        run: |
          cd terraform/infrastructure
          terraform init -backend=false
          # Copy terraform.tfvars values as CLI arguments in case tfvars file is not picked up
          terraform apply -auto-approve \
            -var="aws_region=$AWS_DEFAULT_REGION" \
            -var="eks_cluster_name=$CLUSTER_NAME" \
            -var="vpc_id=vpc-02fb1f16ffa2c1a11" \
            -var="cloudwatch_log_group_name=/aws/eks/barkuni-exam-cluster/cluster" \
            -var="kms_key_id=arn:aws:kms:us-east-1:058264138725:key/c600ebf9-94ec-4cf6-9e5a-1403967190d2" \
            -var="domain_name=vicarius.xyz" \
            -var="organization_name=Barkuni" \
            -var="node_group_name=general" \
            -var="node_role_arn=arn:aws:iam::058264138725:role/general-eks-node-group-20250520133836818000000001" \
            -var="node_desired_size=2" \
            -var="node_min_size=1" \
            -var="node_max_size=3" \
            -var='node_instance_types=["t3.medium"]' \
            -var="project_name=barkuni"
      - name: Wait for EKS Cluster and Node Group
        run: |
          for i in {1..30}; do 
            STATUS=$(aws eks describe-cluster --name $CLUSTER_NAME --region $AWS_DEFAULT_REGION --query "cluster.status" --output text)
            echo "EKS cluster status: $STATUS"
            if [ "$STATUS" = "ACTIVE" ]; then break; fi
            sleep 20
          done
          for i in {1..30}; do 
            STATUS=$(aws eks describe-nodegroup --cluster-name $CLUSTER_NAME --nodegroup-name general --region $AWS_DEFAULT_REGION --query "nodegroup.status" --output text)
            echo "Node group status: $STATUS"
            if [ "$STATUS" = "ACTIVE" ]; then break; fi
            sleep 20
          done
      - name: Wait for EKS API Server
        run: |
          echo "Checking EKS API server connectivity..."
          for i in {1..45}; do
            if aws eks describe-cluster --name $CLUSTER_NAME --query cluster.status --output text; then
              if curl -k -m 10 "https://$(aws eks describe-cluster --name $CLUSTER_NAME --query 'cluster.endpoint' --output text | sed 's/https:\/\///')/healthz"; then
                echo "EKS API is accessible"
                break
              fi
            fi
            echo "Waiting for EKS API to be accessible... Attempt $i"
            sleep 20
          done

      - name: Configure kubectl with retry
        run: |
          for i in {1..5}; do
            if aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_DEFAULT_REGION; then
              echo "kubectl configured successfully"
              break
            fi
            echo "Retrying kubectl configuration... Attempt $i"
            sleep 10
          done
          
          # Verify connectivity
          for i in {1..5}; do
            if kubectl get nodes; then
              echo "Kubernetes cluster is accessible"
              break
            fi
            echo "Waiting for cluster access... Attempt $i"
            sleep 10
          done

      - name: Deploy Application with Helm & Install NGINX
        run: |
          kubectl get namespace barkuni || kubectl create namespace barkuni --request-timeout=60s
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          
          # Install Helm charts with increased timeout
          helm upgrade --install barkuni-api ./helm/barkuni-api \
            --namespace barkuni \
            --wait \
            --timeout 10m \
            --set connectTimeout=300
          
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
            --namespace ingress-nginx \
            --create-namespace \
            --set controller.publishService.enabled=true \
            --set controller.service.externalTrafficPolicy=Local \
            --set controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-type"="nlb" \
            --timeout 10m
      - name: Get NGINX Ingress LB DNS Name
        id: nginx_lb
        run: |
          for i in {1..30}; do
            LB_DNS=$(kubectl get svc ingress-nginx-controller -n ingress-nginx -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
            if [ -n "$LB_DNS" ]; then
              echo "nginx_lb_dns_name=$LB_DNS" >> $GITHUB_OUTPUT
              break
            fi
            echo "Waiting for NGINX Ingress LB DNS name..."
            sleep 10
          done
          if [ -z "$LB_DNS" ]; then
            echo "ERROR: NGINX Ingress LoadBalancer DNS name not found." >&2
            exit 1
          fi
  deploy-dns:
    needs: deploy-infra
    runs-on: ubuntu-latest
    container:
      image: muzaparoff/terraform-runner:latest
      options: --platform=linux/amd64
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Init (DNS)
        run: |
          cd terraform/dns
          terraform init -backend=false
      - name: Terraform Apply (DNS)
        run: |
          cd terraform/dns
          echo "nginx_lb_dns_name=${{ steps.nginx_lb.outputs.nginx_lb_dns_name }}"
          terraform apply -auto-approve -var="nginx_lb_dns_name=${{ steps.nginx_lb.outputs.nginx_lb_dns_name }}"